services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: mcp-ambari-api-open-webui
    ports:
      - "3001:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  mcp-server:
    image: call518/mcp-server-ambari-api:1.0.0
    container_name: mcp-ambari-api-mcp-server
    ports:
      - "18001:18000"
    environment:
      - PYTHONPATH=/app/src
      - FASTMCP_HOST=0.0.0.0
      - FASTMCP_PORT=18000
      - AMBARI_HOST=host.docker.internal
      - AMBARI_PORT=7070
      - AMBARI_USER=admin
      - AMBARI_PASS=changeme!@34
      - AMBARI_CLUSTER_NAME=TEST-AMBARI
      - AMBARI_LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src/
      - ./scripts:/app/scripts
    restart: always

  mcpo-proxy:
    image: call518/mcpo-proxy-ambari-api:1.0.2
    container_name: mcp-ambari-api-mcpo-proxy
    depends_on:
      - mcp-server
    ports:
      - "8001:8000"
    volumes:
      - ./mcp-config.json.http:/app/config/mcp-config.json
      - ./src:/app/src
    restart: always

volumes:
  open-webui-data:
    name: open-webui-data-mcp-ambari-api
