services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: mcp-ambari-api-open-webui
    ports:
      - "${DOCKER_EXTERNAL_PORT_OPENWEBUI}:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  mcp-server:
    image: call518/mcp-server-ambari-api:1.0.0
    container_name: mcp-ambari-api-mcp-server
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCP_SERVER}:8000" ### (WARNING) Must be same with port number of 'FASTMCP_PORT', 'mcp-config.json' and 'mcp-config.json.http'
    environment:
      - PYTHONPATH=${PYTHONPATH}
      - FASTMCP_TYPE=${FASTMCP_TYPE}
      - FASTMCP_HOST=${FASTMCP_HOST}
      - FASTMCP_PORT=${FASTMCP_PORT}
      - AMBARI_HOST=${AMBARI_HOST}
      - AMBARI_PORT=${AMBARI_PORT}
      - AMBARI_USER=${AMBARI_USER}
      - AMBARI_PASS=${AMBARI_PASS}
      - AMBARI_CLUSTER_NAME=${AMBARI_CLUSTER_NAME}
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL}
    volumes:
      - ./src:/app/src/
      - ./scripts:/app/scripts
      - ./.env:/app/.env:ro
    restart: unless-stopped

  mcpo-proxy:
    image: call518/mcpo-proxy-ambari-api:1.0.2
    container_name: mcp-ambari-api-mcpo-proxy
    depends_on:
      - mcp-server
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCPO_PROXY}:8000"
    volumes:
      - ./mcp-config.json.http:/app/config/mcp-config.json
      - ./src:/app/src
    restart: unless-stopped

volumes:
  open-webui-data:
    name: open-webui-data-mcp-ambari-api
