#!/bin/bash

export PYTHONPATH=${PYTHONPATH}
export FASTMCP_HOST=${FASTMCP_HOST}
export FASTMCP_PORT=${FASTMCP_PORT}
export AMBARI_HOST=${AMBARI_HOST}
export AMBARI_PORT=${AMBARI_PORT}
export AMBARI_USER=${AMBARI_USER}
export AMBARI_PASS=${AMBARI_PASS}
export AMBARI_CLUSTER_NAME=${AMBARI_CLUSTER_NAME}
export AMBARI_LOG_LEVEL=${AMBARI_LOG_LEVEL}

python -m mcp_ambari_api.ambari_api
